# Generated by Django 3.0.3 on 2024-03-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secucam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footage',
            name='footage_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
